"""add rentals schema

Revision ID: 7bc2c739d594
Revises: 0001_initial
Create Date: 2026-09-12 11:07:13.640652

The five tables from docs/er-diagram.md. Autogenerated, then reviewed; the only
hand edit is dropping the enum types at the end of downgrade().
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bc2c739d594"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenities")),
        sa.UniqueConstraint("name", name=op.f("uq_amenities_name")),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("locality", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "property_type",
            sa.Enum("apartment", "independent_house", "villa", "studio", name="property_type"),
            nullable=False,
        ),
        sa.Column(
            "furnishing",
            sa.Enum("unfurnished", "semi_furnished", "fully_furnished", name="furnishing"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("available", "rented", "inactive", name="property_status"),
            nullable=False,
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("monthly_rent", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("security_deposit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("carpet_area_sqft", sa.Integer(), nullable=True),
        sa.Column("available_from", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("bedrooms >= 0", name=op.f("ck_properties_bedrooms_non_negative")),
        sa.CheckConstraint(
            "carpet_area_sqft > 0", name=op.f("ck_properties_carpet_area_sqft_positive")
        ),
        sa.CheckConstraint(
            "monthly_rent >= 0", name=op.f("ck_properties_monthly_rent_non_negative")
        ),
        sa.CheckConstraint(
            "security_deposit >= 0", name=op.f("ck_properties_security_deposit_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_properties_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
    )
    op.create_index(op.f("ix_properties_location_id"), "properties", ["location_id"], unique=False)
    op.create_table(
        "property_amenities",
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("amenity_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name=op.f("fk_property_amenities_amenity_id_amenities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_property_amenities_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("property_id", "amenity_id", name=op.f("pk_property_amenities")),
    )
    op.create_index(
        op.f("ix_property_amenities_amenity_id"), "property_amenities", ["amenity_id"], unique=False
    )
    op.create_table(
        "property_images",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2083), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_property_images_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_property_images_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_images")),
    )
    op.create_index(
        op.f("ix_property_images_property_id"), "property_images", ["property_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_property_images_property_id"), table_name="property_images")
    op.drop_table("property_images")
    op.drop_index(op.f("ix_property_amenities_amenity_id"), table_name="property_amenities")
    op.drop_table("property_amenities")
    op.drop_index(op.f("ix_properties_location_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_table("locations")
    op.drop_table("amenities")
    # ### end Alembic commands ###

    # Added by hand -- Alembic never generates these. create_table() created the
    # enum types implicitly, but drop_table() does not drop them, so without this
    # the next upgrade fails with 'type "property_type" already exists'.
    bind = op.get_bind()
    for enum_name in ("property_status", "furnishing", "property_type"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=False)
